export const FETCH_WEATHERAPI_DATA_REQUEST = "FETCH_WEATHERAPI_DATA_REQUEST";
export const FETCH_WEATHERAPI_DATA_SUCCESS = "FETCH_WEATHERAPI_DATA_SUCCESS";
export const FETCH_WEATHERAPI_DATA_FAILURE = "FETCH_WEATHERAPI_DATA_FAILURE";

